ansible_host: 172.22.174.25

telegraf_deb_url: https://dl.influxdata.com/telegraf/releases/telegraf_1.14.5-1_arm64.deb

service_name: infra
service_name_influxdb: gitlab_runners

disk:
  mount_points:
    - "/mnt/disk"
