- name: add influxdb database
  influxdb_database:
    hostname: "{{ influxdb_host }}"
    database_name: "{{ influxdb_database }}"
    database_state: present
    module_auth: true
  delegate_to: "{{ influxdb_inventory_hostname }}"

- name: add user to unfluxdb, allow database access, create default database retention policy
  influxdb_database:
    hostname: "{{ influxdb_host }}"
    username: "{{ influxdb_username }}"
    password: "{{ influxdb_password }}"
    allow_database: "{{ influxdb_database }}"
    module_auth: true
  delegate_to: "{{ influxdb_inventory_hostname }}"